version: 2
project_name: bytefreezer-proxy
before:
  hooks:
    - go mod tidy
builds:
  - id: bin
    main: ./cmd/bytefreezer-proxy
    env:
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
archives:
  - id: tgz
    builds: [bin]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
changelog:
  use: git
release:
  draft: false
