app:
  name: bytefreezer-proxy
  version: 0.0.1

# Logging configuration   
logging:
  level: debug
  encoding: console

# API server configuration
server:
  api_port: 8088

# UDP listener configuration
udp:
  enabled: true
  host: "0.0.0.0"
  read_buffer_size_bytes: 134217728  # 128MB
  max_batch_lines: 100000
  max_batch_bytes: 268435456  # 256MB  
  batch_timeout_seconds: 30
  compression_level: 6
  enable_compression: true
  
  # Port configuration with dataset mapping
  listeners:
    - port: 2056
      dataset_id: "syslog-data"
      # tenant_id: "custom-tenant"  # Optional: overrides global tenant
    - port: 2057  
      dataset_id: "ebpf-data"
    - port: 2058
      dataset_id: "application-logs"

# Global tenant configuration
tenant_id: "customer-1"
bearer_token: "bearer-token-customer-1-dev"

# Bytefreezer-receiver configuration
receiver:
  base_url: "http://localhost:8080/data/{tenantid}/{datasetid}"
  timeout_seconds: 30
  retry_count: 3
  retry_delay_seconds: 1

# SOC alerting configuration
soc:
  enabled: false
  endpoint: ""
  timeout: 30

# OpenTelemetry configuration
otel:
  enabled: false
  endpoint: "10.0.32.106:4317"
  service_name: "bytefreezer-proxy"
  scrapeIntervalseconds: 100

# Housekeeping configuration
housekeeping:
  enabled: true
  intervalseconds: 60

# Local spooling for failed uploads
spooling:
  enabled: true
  directory: "/tmp/bytefreezer-proxy"
  max_size_bytes: 1073741824  # 1GB
  retry_attempts: 5
  retry_interval_seconds: 60  # 1 minute
  cleanup_interval_seconds: 300  # 5 minutes

# Development mode
dev: false