---
# AWX Job Template: ByteFreezer Proxy Deployment
# Import this configuration into AWX

name: "ByteFreezer Proxy - Deploy"
description: "Deploy ByteFreezer Proxy to target hosts with full installation and configuration"
job_type: "run"
inventory: "ByteFreezer Proxy Servers"
project: "ByteFreezer Proxy"
playbook: "playbooks/deploy.yml"
credential: "ByteFreezer Proxy SSH"
vault_credential: null
forks: 5
limit: ""
verbosity: 1
extra_vars: |
  # Override default variables here
  bytefreezer_proxy_version: "latest"
  bytefreezer_proxy_systemd_started: true
job_tags: ""
skip_tags: ""
start_at_task: ""
timeout: 3600
use_fact_cache: true
host_config_key: ""
ask_scm_branch_on_launch: false
ask_variables_on_launch: true
ask_limit_on_launch: true
ask_tags_on_launch: true
ask_skip_tags_on_launch: true
ask_job_type_on_launch: false
ask_verbosity_on_launch: true
ask_inventory_on_launch: false
ask_credential_on_launch: false
survey_enabled: true
become_enabled: true
diff_mode: false
allow_simultaneous: false
custom_virtualenv: null
job_slice_count: 1
webhook_service: ""
webhook_credential: null

# Survey specification for interactive deployment
survey_spec:
  name: "Deployment Configuration"
  description: "Configure deployment parameters"
  spec:
    - question_name: "Target Environment"
      question_description: "Select the environment to deploy to"
      required: true
      type: "multiplechoice"
      variable: "deployment_environment"
      min: 0
      max: 1024
      default: "production"
      choices:
        - "production"
        - "staging" 
        - "development"
        - "all"

    - question_name: "ByteFreezer Proxy Version"
      question_description: "Version to deploy (latest, v1.0.0, etc.)"
      required: true
      type: "text"
      variable: "bytefreezer_proxy_version"
      min: 1
      max: 50
      default: "latest"

    - question_name: "Receiver Base URL"
      question_description: "ByteFreezer Receiver endpoint URL"
      required: false
      type: "text"
      variable: "receiver_base_url_override"
      min: 0
      max: 255
      default: ""

    - question_name: "Tenant ID Override"
      question_description: "Override tenant ID for all hosts"
      required: false
      type: "text"
      variable: "tenant_id_override"
      min: 0
      max: 100
      default: ""

    - question_name: "Start Service After Deployment"
      question_description: "Start the service immediately after deployment"
      required: true
      type: "multiplechoice"
      variable: "start_service_after_deploy"
      min: 0
      max: 1024
      default: "true"
      choices:
        - "true"
        - "false"

    - question_name: "Enable System Tuning"
      question_description: "Apply system tuning for UDP performance"
      required: true
      type: "multiplechoice"
      variable: "enable_system_tuning"
      min: 0
      max: 1024
      default: "true"
      choices:
        - "true"
        - "false"

    - question_name: "Configure Firewall"
      question_description: "Automatically configure firewall rules"
      required: true
      type: "multiplechoice"
      variable: "configure_firewall"
      min: 0
      max: 1024
      default: "true"
      choices:
        - "true"
        - "false"

    - question_name: "Enable Backups"
      question_description: "Create backups before deployment"
      required: true
      type: "multiplechoice"  
      variable: "enable_backups"
      min: 0
      max: 1024
      default: "true"
      choices:
        - "true"
        - "false"

    - question_name: "UDP Port Configuration"
      question_description: "Configure UDP listeners (JSON format: [{\"port\": 2056, \"dataset_id\": \"syslog-data\"}])"
      required: false
      type: "textarea"
      variable: "udp_listeners_override"
      min: 0
      max: 1024
      default: '[{"port": 2056, "dataset_id": "syslog-data"}]'

    - question_name: "Spooling Directory"
      question_description: "Local spooling directory for failed uploads"
      required: false
      type: "text"
      variable: "spooling_directory_override"
      min: 0
      max: 255
      default: "/var/spool/bytefreezer-proxy"

    - question_name: "Enable Spooling"
      question_description: "Enable local spooling for failed uploads"
      required: true
      type: "multiplechoice"
      variable: "enable_spooling"
      min: 0
      max: 1024
      default: "true"
      choices:
        - "true"
        - "false"

# Extra variables template
extra_vars_template: |
  # Deployment configuration from survey
  {% if deployment_environment != "all" %}
  ansible_limit: "{{ deployment_environment }}"
  {% endif %}
  
  bytefreezer_proxy_version: "{{ bytefreezer_proxy_version | default('latest') }}"
  bytefreezer_proxy_systemd_started: {{ start_service_after_deploy | default('true') | bool }}
  bytefreezer_proxy_system_tuning_enabled: {{ enable_system_tuning | default('true') | bool }}
  bytefreezer_proxy_firewall_enabled: {{ configure_firewall | default('true') | bool }}
  bytefreezer_proxy_backup_enabled: {{ enable_backups | default('true') | bool }}
  
  # Configuration overrides
  {% if receiver_base_url_override %}
  receiver_base_url_global_override: "{{ receiver_base_url_override }}"
  {% endif %}
  
  {% if tenant_id_override %}
  tenant_id_global_override: "{{ tenant_id_override }}"
  {% endif %}
  
  # UDP and Spooling configuration overrides
  {% if udp_listeners_override %}
  bytefreezer_proxy_config:
    udp:
      listeners: {{ udp_listeners_override | from_json }}
  {% endif %}
  
  {% if spooling_directory_override %}
  bytefreezer_proxy_spooling_dir: "{{ spooling_directory_override }}"
  {% endif %}
  
  {% if enable_spooling is defined %}
  spooling_enabled_override: {{ enable_spooling | bool }}
  {% endif %}