---
# AWX Job Template: Service Management
# Import this configuration into AWX

name: "ByteFreezer Proxy - Service Management"
description: "Start, stop, restart, or check status of ByteFreezer Proxy service"
job_type: "run"
inventory: "ByteFreezer Proxy Servers"
project: "ByteFreezer Proxy"
playbook: "playbooks/manage-service.yml"
credential: "ByteFreezer Proxy SSH"
vault_credential: null
forks: 10
limit: ""
verbosity: 1
extra_vars: |
  action: "status"
job_tags: ""
skip_tags: ""
start_at_task: ""
timeout: 900
use_fact_cache: true
host_config_key: ""
ask_scm_branch_on_launch: false
ask_variables_on_launch: true
ask_limit_on_launch: true
ask_tags_on_launch: false
ask_skip_tags_on_launch: false
ask_job_type_on_launch: false
ask_verbosity_on_launch: true
ask_inventory_on_launch: false
ask_credential_on_launch: false
survey_enabled: true
become_enabled: true
diff_mode: false
allow_simultaneous: false
custom_virtualenv: null
job_slice_count: 1
webhook_service: ""
webhook_credential: null

# Survey specification for service management
survey_spec:
  name: "Service Management Options"
  description: "Control ByteFreezer Proxy service operations"
  spec:
    - question_name: "Target Environment/Hosts"
      question_description: "Select environment or specific hosts"
      required: true
      type: "text"
      variable: "target_limit"
      min: 1
      max: 100
      default: "production"

    - question_name: "Service Action"
      question_description: "Action to perform on the service"
      required: true
      type: "multiplechoice"
      variable: "service_action"
      min: 0
      max: 1024
      default: "status"
      choices:
        - "status"
        - "start"
        - "stop"
        - "restart"
        - "reload"
        - "enable"
        - "disable"

    - question_name: "Show Recent Logs"
      question_description: "Display recent log entries (for status, start, restart actions)"
      required: true
      type: "multiplechoice"
      variable: "show_logs"
      min: 0
      max: 1024
      default: "true"
      choices:
        - "true"
        - "false"

    - question_name: "Log Lines Count"
      question_description: "Number of recent log lines to show"
      required: false
      type: "text"
      variable: "log_lines"
      min: 0
      max: 10
      default: "20"

    - question_name: "Wait for Health Check"
      question_description: "Wait for health check after start/restart (recommended)"
      required: true
      type: "multiplechoice"
      variable: "wait_for_health"
      min: 0
      max: 1024
      default: "true"
      choices:
        - "true"
        - "false"

    - question_name: "Serial Execution"
      question_description: "Execute on one host at a time (recommended for restarts)"
      required: true
      type: "multiplechoice"
      variable: "serial_execution"
      min: 0
      max: 1024
      default: "false"
      choices:
        - "true"
        - "false"

# Extra variables template for service management
extra_vars_template: |
  # Target and action configuration
  ansible_limit: "{{ target_limit }}"
  action: "{{ service_action }}"
  
  # Additional options
  show_recent_logs: {{ show_logs | default('true') | bool }}
  log_lines_count: {{ log_lines | default('20') | int }}
  wait_for_health_check: {{ wait_for_health | default('true') | bool }}
  
  {% if serial_execution | default('false') | bool %}
  # Serial execution for controlled restarts
  serial: 1
  {% endif %}