---
# AWX Inventory Structure for ByteFreezer Proxy
# Import this into AWX Inventory as YAML

plugin: advanced_host_list

keyed_groups:
  - prefix: env
    key: environment
  - prefix: arch  
    key: ansible_architecture

groups:
  # Environment groups
  production:
    hosts:
      proxy-prod-01:
        ansible_host: 10.1.1.10
        environment: production
        bytefreezer_proxy_config:
          receiver:
            base_url: "http://receiver.prod.example.com:8080"
            tenant_id: "production-tenant"
            dataset_id: "prod-proxy-01"
          udp:
            port: 2056
            max_batch_lines: 100000
          logging:
            level: "info"
          otel:
            enabled: true
            endpoint: "otel-collector.prod.example.com:4317"
      
      proxy-prod-02:
        ansible_host: 10.1.1.11
        environment: production
        bytefreezer_proxy_config:
          receiver:
            base_url: "http://receiver.prod.example.com:8080"
            tenant_id: "production-tenant"  
            dataset_id: "prod-proxy-02"
          udp:
            port: 2056
            max_batch_lines: 100000
          logging:
            level: "info"

  staging:
    hosts:
      proxy-staging-01:
        ansible_host: 10.2.1.10
        environment: staging
        bytefreezer_proxy_config:
          receiver:
            base_url: "http://receiver.staging.example.com:8080"
            tenant_id: "staging-tenant"
            dataset_id: "staging-proxy-01"
          udp:
            port: 2056
            max_batch_lines: 50000
          logging:
            level: "debug"

  development:
    hosts:
      proxy-dev-01:
        ansible_host: 192.168.1.100
        environment: development
        bytefreezer_proxy_config:
          receiver:
            base_url: "http://localhost:8080"
            tenant_id: "dev-tenant"
            dataset_id: "dev-proxy-01"
          udp:
            port: 2056
            max_batch_lines: 10000
          logging:
            level: "debug"
          dev: true

# Global variables for all hosts
all:
  vars:
    # Installation settings
    bytefreezer_proxy_version: "latest"
    bytefreezer_proxy_install_dir: "/opt/bytefreezer-proxy"
    bytefreezer_proxy_config_dir: "/etc/bytefreezer-proxy"
    bytefreezer_proxy_log_dir: "/var/log/bytefreezer-proxy"
    bytefreezer_proxy_user: "bytefreezer"
    bytefreezer_proxy_group: "bytefreezer"
    
    # Service settings
    bytefreezer_proxy_systemd_enabled: true
    bytefreezer_proxy_systemd_started: true
    bytefreezer_proxy_firewall_enabled: true
    bytefreezer_proxy_system_tuning_enabled: true
    
    # Backup settings
    bytefreezer_proxy_backup_enabled: true
    bytefreezer_proxy_backup_dir: "/opt/backups/bytefreezer-proxy"
    bytefreezer_proxy_backup_retention_days: 7