---
- name: Install and configure ByteFreezer Proxy service (GPT recommended approach)
  hosts: all
  become: yes
  vars:
    bytefreezer_user: "bytefreezer"
    bytefreezer_group: "bytefreezer"
    bytefreezer_binary_dest: "/usr/local/bin/bytefreezer-proxy"
    bytefreezer_config_path: "/etc/bytefreezer-proxy/config.yaml"
    bytefreezer_log_dir: "/var/log/bytefreezer-proxy"
    bytefreezer_service_path: "/etc/systemd/system/bytefreezer-proxy.service"
    bytefreezer_logrotate_path: "/etc/logrotate.d/bytefreezer-proxy"
    bytefreezer_spooling_dir: "/var/spool/bytefreezer-proxy"
    bytefreezer_home_dir: "/var/lib/bytefreezer-proxy"
    github_repo: "{{ bytefreezer_proxy_github_repo | default('n0needt0/bytefreezer-proxy') }}"
    version: "{{ bytefreezer_proxy_version | default('latest') }}"
    release_url: "https://api.github.com/repos/{{ github_repo }}/releases/latest"
    binary_name: "bytefreezer-proxy-linux-amd64"

  pre_tasks:
    - name: Check if service already exists
      ansible.builtin.stat:
        path: "{{ bytefreezer_service_path }}"
      register: service_exists

    - name: Fail if service already installed
      fail:
        msg: "ByteFreezer Proxy service is already installed. Use gpt-remove playbook first."
      when: service_exists.stat.exists

  tasks:
    - name: Ensure group exists
      ansible.builtin.group:
        name: "{{ bytefreezer_group }}"
        system: true
      become: yes

    - name: Ensure user exists
      ansible.builtin.user:
        name: "{{ bytefreezer_user }}"
        group: "{{ bytefreezer_group }}"
        system: true
        shell: /usr/sbin/nologin
        home: "{{ bytefreezer_home_dir }}"
        create_home: yes
      become: yes

    - name: Set download URL
      set_fact:
        download_url: "https://github.com/{{ github_repo }}/releases/{{ 'latest/download' if version == 'latest' else 'download/' + version }}/{{ binary_name }}.tar.gz"

    - name: Create temporary directory for download
      ansible.builtin.tempfile:
        state: directory
        suffix: bytefreezer
      register: temp_dir

    - name: Download and extract binary
      ansible.builtin.unarchive:
        src: "{{ download_url }}"
        dest: "{{ temp_dir.path }}"
        remote_src: yes

    - name: Copy binary to /usr/local/bin
      ansible.builtin.copy:
        src: "{{ temp_dir.path }}/{{ binary_name }}"
        dest: "{{ bytefreezer_binary_dest }}"
        mode: '0755'
        owner: root
        group: root
        remote_src: yes
      become: yes

    - name: Clean up temporary directory
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        state: absent

    - name: Ensure config directory exists
      ansible.builtin.file:
        path: "{{ bytefreezer_config_path | dirname }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure runtime/data dir exists
      ansible.builtin.file:
        path: "{{ bytefreezer_home_dir }}"
        state: directory
        owner: "{{ bytefreezer_user }}"
        group: "{{ bytefreezer_group }}"
        mode: "0750"

    - name: Ensure log directory exists
      ansible.builtin.file:
        path: "{{ bytefreezer_log_dir }}"
        state: directory
        owner: "{{ bytefreezer_user }}"
        group: "{{ bytefreezer_group }}"
        mode: "0750"

    - name: Ensure spooling directory exists
      ansible.builtin.file:
        path: "{{ bytefreezer_spooling_dir }}"
        state: directory
        owner: "{{ bytefreezer_user }}"
        group: "{{ bytefreezer_group }}"
        mode: "0750"

    - name: Generate configuration file
      ansible.builtin.template:
        src: config.yaml.j2
        dest: "{{ bytefreezer_config_path }}"
        owner: root
        group: "{{ bytefreezer_group }}"
        mode: '0640'

    - name: Install logrotate configuration
      ansible.builtin.copy:
        dest: "{{ bytefreezer_logrotate_path }}"
        content: |
          {{ bytefreezer_log_dir }}/*.log {
            daily
            rotate 7
            compress
            missingok
            notifempty
            create 0640 {{ bytefreezer_user }} {{ bytefreezer_group }}
            sharedscripts
            postrotate
              systemctl restart bytefreezer-proxy >/dev/null 2>&1 || true
            endscript
          }
        mode: '0644'

    - name: Create systemd service file
      ansible.builtin.copy:
        dest: "{{ bytefreezer_service_path }}"
        content: |
          [Unit]
          Description=ByteFreezer Proxy
          After=network-online.target
          Wants=network-online.target

          [Service]
          User={{ bytefreezer_user }}
          Group={{ bytefreezer_group }}
          WorkingDirectory={{ bytefreezer_home_dir }}
          ExecStart={{ bytefreezer_binary_dest }} --config {{ bytefreezer_config_path }}
          Restart=on-failure
          RestartSec=2s
          LimitNOFILE=65535

          [Install]
          WantedBy=multi-user.target
        mode: '0644'
      notify: Reload systemd

    - name: Enable and start service
      ansible.builtin.systemd:
        name: bytefreezer-proxy
        enabled: yes
        state: started
        daemon_reload: true

    - name: Clean up temporary directory
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        state: absent

  post_tasks:
    - name: Display installation status
      debug:
        msg:
          - "ByteFreezer Proxy installation completed!"
          - "Binary: {{ bytefreezer_binary_dest }}"
          - "Config: {{ bytefreezer_config_path }}"
          - "User: {{ bytefreezer_user }}:{{ bytefreezer_group }}"
          - "Home: {{ bytefreezer_home_dir }}"
          - "Logs: {{ bytefreezer_log_dir }}"
          - "Spooling: {{ bytefreezer_spooling_dir }}"
          - "Service: systemctl status bytefreezer-proxy"

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true