---
- name: Install and configure ByteFreezer Proxy service
  hosts: all
  become: yes

  pre_tasks:
    - name: Check if service already exists
      ansible.builtin.stat:
        path: "{{ paths.service_path }}"
      register: service_exists

    - name: Fail if service already installed
      fail:
        msg: "ByteFreezer Proxy service is already installed. Use remove playbook first."
      when: service_exists.stat.exists

  tasks:
    - name: Create temporary directory for download
      ansible.builtin.tempfile:
        state: directory
        suffix: bytefreezer
      register: temp_dir

    - name: Download and extract binary
      ansible.builtin.unarchive:
        src: "{{ download.url }}"
        dest: "{{ temp_dir.path }}"
        remote_src: yes
      
    - name: Copy binary to destination
      ansible.builtin.copy:
        src: "{{ temp_dir.path }}/bytefreezer-proxy-linux-amd64"
        dest: "{{ paths.binary_path }}"
        owner: root
        group: root
        mode: '0755'
        remote_src: yes
      become: yes

    - name: Ensure config directory exists
      ansible.builtin.file:
        path: "{{ paths.config_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      become: yes

    - name: Ensure log directory exists
      ansible.builtin.file:
        path: "{{ paths.log_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      become: yes
      
    - name: Ensure spooling directory exists
      ansible.builtin.file:
        path: "{{ paths.spool_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      become: yes
      
    - name: Generate configuration file
      ansible.builtin.template:
        src: config.yaml.j2
        dest: "/tmp/config.yaml"
        mode: '0644'
        
    - name: Copy configuration file to final location
      ansible.builtin.copy:
        src: "/tmp/config.yaml"
        dest: "{{ paths.config_path }}"
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      become: yes
      
    - name: Install logrotate configuration
      ansible.builtin.template:
        src: logrotate.j2
        dest: "/tmp/logrotate"
        mode: '0644'
        
    - name: Copy logrotate configuration to final location
      ansible.builtin.copy:
        src: "/tmp/logrotate"
        dest: "{{ paths.logrotate_path }}"
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      become: yes
      
    - name: Create systemd service file
      ansible.builtin.template:
        src: bytefreezer-proxy.service.j2
        dest: "/tmp/bytefreezer-proxy.service"
        mode: '0644'
        
    - name: Copy service file to final location
      ansible.builtin.copy:
        src: "/tmp/bytefreezer-proxy.service"
        dest: "{{ paths.service_path }}"
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      become: yes

    - name: Enable and start service
      ansible.builtin.systemd:
        name: "{{ service.name }}"
        enabled: yes
        state: started
        daemon_reload: yes
      become: yes

    - name: Clean up temporary directory
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        state: absent
        
    - name: Clean up template files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/config.yaml"
        - "/tmp/logrotate"
        - "/tmp/bytefreezer-proxy.service"

  post_tasks:
    - name: Display installation status
      debug:
        msg:
          - "ByteFreezer Proxy installation completed!"
          - "Binary: {{ paths.binary_path }}"
          - "Config: {{ paths.config_path }}"
          - "Logs: {{ paths.log_dir }}"
          - "Spooling: {{ paths.spool_dir }}"
          - "Service: systemctl status {{ service.name }}"