---
# ByteFreezer Proxy Removal Playbook (Simplified - Service Only)
- name: Remove ByteFreezer Proxy
  hosts: all
  become: yes
  gather_facts: true

  vars:
    # Default values for all variables used in playbook
    service_name: "{{ bytefreezer_proxy_service_name | default('bytefreezer-proxy') }}"
    user_name: "{{ bytefreezer_proxy_user | default('bytefreezer') }}"
    group_name: "{{ bytefreezer_proxy_group | default('bytefreezer') }}"
    install_dir: "{{ bytefreezer_proxy_install_dir | default('/opt/bytefreezer-proxy') }}"
    config_dir: "{{ bytefreezer_proxy_config_dir | default('/etc/bytefreezer-proxy') }}"
    log_dir: "{{ bytefreezer_proxy_log_dir | default('/var/log/bytefreezer-proxy') }}"
    spooling_dir: "{{ bytefreezer_proxy_spooling_dir | default('/var/spool/bytefreezer-proxy') }}"
    backup_on_remove: "{{ bytefreezer_proxy_backup_on_remove | default(false) }}"
    backup_dir: "{{ bytefreezer_proxy_backup_dir | default('/opt/backups/bytefreezer-proxy') }}"
    remove_spooling_dir: "{{ bytefreezer_proxy_remove_spooling_dir | default(false) }}"

  pre_tasks:
    - name: Check if service exists
      ansible.builtin.stat:
        path: /etc/systemd/system/{{ service_name }}.service
      register: service_exists

    - name: Wait for apt lock to be released
      ansible.builtin.wait_for:
        path: /var/lib/dpkg/lock-frontend
        state: absent
        timeout: 300
      when: ansible_os_family == 'Debian'
      become: yes
      ignore_errors: yes

    - name: Display removal information
      debug:
        msg:
          - "Removing ByteFreezer Proxy service..."
          - "Service exists: {{ service_exists.stat.exists }}"
          - "Backup data: {{ backup_on_remove }}"

  tasks:
    - name: Stop and disable service
      systemd:
        name: "{{ service_name }}"
        state: stopped
        enabled: no
        daemon_reload: yes
      when: service_exists.stat.exists
      ignore_errors: yes

    - name: Create backup directory
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      when: backup_on_remove | default(false)

    - name: Backup configuration and data
      ansible.builtin.shell: |
        tar -czf "{{ backup_dir }}/bytefreezer-proxy-removal-backup-{{ ansible_date_time.epoch }}.tar.gz" \
          --ignore-failed-read \
          "{{ config_dir }}" \
          "{{ log_dir }}" \
          "{{ spooling_dir }}" \
          2>/dev/null || true
      when: backup_on_remove | default(false)
      ignore_errors: yes

    - name: Remove systemd service file
      ansible.builtin.file:
        path: /etc/systemd/system/{{ service_name }}.service
        state: absent
      notify: reload systemd

    - name: Remove logrotate configuration
      ansible.builtin.file:
        path: /etc/logrotate.d/bytefreezer-proxy
        state: absent

    - name: Remove installation directory
      ansible.builtin.file:
        path: "{{ install_dir }}"
        state: absent

    - name: Remove configuration directory
      ansible.builtin.file:
        path: "{{ config_dir }}"
        state: absent

    - name: Remove log directory
      ansible.builtin.file:
        path: "{{ log_dir }}"
        state: absent

    - name: Remove spooling directory (only if explicitly requested)
      ansible.builtin.file:
        path: "{{ spooling_dir }}"
        state: absent
      when: remove_spooling_dir | default(false)

    - name: Remove system user
      ansible.builtin.user:
        name: "{{ user_name }}"
        state: absent
        remove: yes

    - name: Remove system group
      ansible.builtin.group:
        name: "{{ group_name }}"
        state: absent

  post_tasks:
    - name: Verify removal
      ansible.builtin.stat:
        path: /etc/systemd/system/{{ service_name }}.service
      register: service_removed

    - name: Display removal status
      debug:
        msg:
          - "ByteFreezer Proxy complete removal completed!"
          - "Service removed: {{ not service_removed.stat.exists }}"
          - "Directories removed: {{ install_dir }}, {{ config_dir }}, {{ log_dir }}"
          - "Spooling directory preserved: {{ spooling_dir }} (unless bytefreezer_proxy_remove_spooling_dir=true)"
          - "System user and group removed"
          - "Backup created: {{ backup_on_remove }}"
          - "NOTE: Firewall rules and system tuning must be reverted manually"

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes