---
- name: Remove ByteFreezer Proxy service
  hosts: all
  become: yes
  vars:
    bytefreezer_binary_dest: "/usr/local/bin/bytefreezer-proxy"
    bytefreezer_config_dir: "/etc/bytefreezer-proxy"
    bytefreezer_log_dir: "/var/log/bytefreezer-proxy"
    bytefreezer_service_path: "/etc/systemd/system/bytefreezer-proxy.service"
    bytefreezer_logrotate_path: "/etc/logrotate.d/bytefreezer-proxy"
    bytefreezer_spooling_dir: "/var/spool/bytefreezer-proxy"
    remove_spooling_dir: "{{ bytefreezer_proxy_remove_spooling_dir | default(false) }}"

  pre_tasks:
    - name: Check if service exists
      ansible.builtin.stat:
        path: "{{ bytefreezer_service_path }}"
      register: service_exists

    - name: Display removal information
      debug:
        msg:
          - "Removing ByteFreezer Proxy service..."
          - "Service exists: {{ service_exists.stat.exists }}"

  tasks:
    - name: Stop and disable service
      ansible.builtin.shell: |
        sudo systemctl stop bytefreezer-proxy || true
        sudo systemctl disable bytefreezer-proxy || true
        timeout 30 sudo systemctl daemon-reload || echo "daemon-reload completed or timed out"
      when: service_exists.stat.exists
      ignore_errors: yes


    - name: Remove systemd service file
      ansible.builtin.shell: |
        sudo rm -f "{{ bytefreezer_service_path }}"
        timeout 30 sudo systemctl daemon-reload || echo "daemon-reload completed or timed out"
      ignore_errors: yes

    - name: Remove logrotate configuration
      ansible.builtin.shell: |
        sudo rm -f "{{ bytefreezer_logrotate_path }}"
      ignore_errors: yes

    - name: Remove binary
      ansible.builtin.shell: |
        sudo rm -f "{{ bytefreezer_binary_dest }}"
      ignore_errors: yes

    - name: Remove configuration directory
      ansible.builtin.shell: |
        sudo rm -rf "{{ bytefreezer_config_dir }}"
      ignore_errors: yes

    - name: Remove log directory
      ansible.builtin.shell: |
        sudo rm -rf "{{ bytefreezer_log_dir }}"
      ignore_errors: yes

    - name: Remove spooling directory (only if explicitly requested)
      ansible.builtin.shell: |
        sudo rm -rf "{{ bytefreezer_spooling_dir }}"
      when: remove_spooling_dir
      ignore_errors: yes

  post_tasks:
    - name: Verify removal
      ansible.builtin.stat:
        path: "{{ bytefreezer_service_path }}"
      register: service_removed

    - name: Display removal status
      debug:
        msg:
          - "ByteFreezer Proxy removal completed!"
          - "Service removed: {{ not service_removed.stat.exists }}"
          - "Binary removed: {{ bytefreezer_binary_dest }}"
          - "Directories removed: {{ bytefreezer_config_dir }}, {{ bytefreezer_log_dir }}"
          - "Spooling directory preserved: {{ bytefreezer_spooling_dir }} (unless remove_spooling_dir=true)"

