---
# ByteFreezer Proxy Removal Playbook (Remove Only)
- name: Remove ByteFreezer Proxy
  hosts: bytefreezer_proxy
  become: true
  gather_facts: true

  vars:
    # AWX compatibility - merge survey variables with host-specific config
    merged_config: "{{ bytefreezer_proxy_default_config | combine(bytefreezer_proxy_config | default({}), recursive=True) }}"

  pre_tasks:
    - name: Check if service exists
      ansible.builtin.stat:
        path: /etc/systemd/system/{{ bytefreezer_proxy_service_name }}.service
      register: service_exists

    - name: Display removal information
      debug:
        msg:
          - "Removing ByteFreezer Proxy service..."
          - "Service exists: {{ service_exists.stat.exists }}"
          - "Backup data: {{ bytefreezer_proxy_backup_on_remove | default(false) }}"

  tasks:
    - name: Stop and disable service
      systemd:
        name: "{{ bytefreezer_proxy_service_name }}"
        state: stopped
        enabled: no
        daemon_reload: yes
      when: service_exists.stat.exists
      ignore_errors: yes

    - name: Create backup directory
      ansible.builtin.file:
        path: "{{ bytefreezer_proxy_backup_dir | default('/opt/backups/bytefreezer-proxy') }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      when: bytefreezer_proxy_backup_on_remove | default(false)

    - name: Backup configuration and data
      ansible.builtin.shell: |
        tar -czf "{{ bytefreezer_proxy_backup_dir | default('/opt/backups/bytefreezer-proxy') }}/bytefreezer-proxy-removal-backup-{{ ansible_date_time.epoch }}.tar.gz" \
          --ignore-failed-read \
          "{{ bytefreezer_proxy_config_dir }}" \
          "{{ bytefreezer_proxy_log_dir }}" \
          "{{ bytefreezer_proxy_spooling_dir }}" \
          2>/dev/null || true
      when: bytefreezer_proxy_backup_on_remove | default(false)
      ignore_errors: yes

    - name: Remove systemd service file
      ansible.builtin.file:
        path: /etc/systemd/system/{{ bytefreezer_proxy_service_name }}.service
        state: absent
      notify: reload systemd

    - name: Remove logrotate configuration
      ansible.builtin.file:
        path: /etc/logrotate.d/bytefreezer-proxy
        state: absent

    - name: Remove firewall rules (ufw)
      ufw:
        rule: allow
        port: "{{ bytefreezer_proxy_api_port }}"
        proto: tcp
        delete: yes
      when: 
        - bytefreezer_proxy_firewall_enabled
        - ansible_os_family == "Debian"
      ignore_errors: yes

    - name: Remove UDP firewall rules (ufw)
      ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: udp
        delete: yes
      loop: "{{ merged_config.udp.listeners }}"
      when: 
        - bytefreezer_proxy_firewall_enabled
        - ansible_os_family == "Debian"
      ignore_errors: yes

    - name: Remove firewall rules (firewalld)
      firewalld:
        port: "{{ bytefreezer_proxy_api_port }}/tcp"
        permanent: yes
        state: disabled
        immediate: yes
      when:
        - bytefreezer_proxy_firewall_enabled 
        - ansible_os_family == "RedHat"
      ignore_errors: yes

    - name: Remove UDP firewall rules (firewalld)
      firewalld:
        port: "{{ item.port }}/udp"
        permanent: yes
        state: disabled
        immediate: yes
      loop: "{{ merged_config.udp.listeners }}"
      when:
        - bytefreezer_proxy_firewall_enabled 
        - ansible_os_family == "RedHat"
      ignore_errors: yes

    - name: Remove installation directory
      ansible.builtin.file:
        path: "{{ bytefreezer_proxy_install_dir }}"
        state: absent

    - name: Remove configuration directory
      ansible.builtin.file:
        path: "{{ bytefreezer_proxy_config_dir }}"
        state: absent

    - name: Remove log directory
      ansible.builtin.file:
        path: "{{ bytefreezer_proxy_log_dir }}"
        state: absent

    - name: Remove spooling directory
      ansible.builtin.file:
        path: "{{ bytefreezer_proxy_spooling_dir }}"
        state: absent

    - name: Remove system user
      ansible.builtin.user:
        name: "{{ bytefreezer_proxy_user }}"
        state: absent
        remove: yes

    - name: Remove system group
      ansible.builtin.group:
        name: "{{ bytefreezer_proxy_group }}"
        state: absent

    - name: Remove system tuning (reset to defaults)
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.default_value }}"
        state: present
        reload: yes
      loop:
        - { name: "net.core.rmem_max", default_value: "212992" }
        - { name: "net.core.rmem_default", default_value: "212992" }
        - { name: "net.core.wmem_max", default_value: "212992" }
        - { name: "net.core.wmem_default", default_value: "212992" }
        - { name: "net.core.netdev_max_backlog", default_value: "1000" }
      when: bytefreezer_proxy_system_tuning_enabled

  post_tasks:
    - name: Verify removal
      ansible.builtin.stat:
        path: /etc/systemd/system/{{ bytefreezer_proxy_service_name }}.service
      register: service_removed

    - name: Display removal status
      debug:
        msg:
          - "ByteFreezer Proxy complete removal completed!"
          - "Service removed: {{ not service_removed.stat.exists }}"
          - "All directories removed: {{ bytefreezer_proxy_install_dir }}, {{ bytefreezer_proxy_config_dir }}, {{ bytefreezer_proxy_log_dir }}, {{ bytefreezer_proxy_spooling_dir }}"
          - "System user and group removed"
          - "System tuning reset to defaults"
          - "Firewall rules removed"
          - "Backup created: {{ bytefreezer_proxy_backup_on_remove | default(false) }}"

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes