---
# ByteFreezer Proxy Removal Playbook (Simplified - Service Only)
- name: Remove ByteFreezer Proxy
  hosts: all
  become: true
  gather_facts: true

  vars:
    # Default values for all variables used in playbook
    bytefreezer_proxy_service_name: "{{ bytefreezer_proxy_service_name | default('bytefreezer-proxy') }}"
    bytefreezer_proxy_user: "{{ bytefreezer_proxy_user | default('bytefreezer') }}"
    bytefreezer_proxy_group: "{{ bytefreezer_proxy_group | default('bytefreezer') }}"
    bytefreezer_proxy_install_dir: "{{ bytefreezer_proxy_install_dir | default('/opt/bytefreezer-proxy') }}"
    bytefreezer_proxy_config_dir: "{{ bytefreezer_proxy_config_dir | default('/etc/bytefreezer-proxy') }}"
    bytefreezer_proxy_log_dir: "{{ bytefreezer_proxy_log_dir | default('/var/log/bytefreezer-proxy') }}"
    bytefreezer_proxy_spooling_dir: "{{ bytefreezer_proxy_spooling_dir | default('/var/spool/bytefreezer-proxy') }}"
    bytefreezer_proxy_backup_on_remove: "{{ bytefreezer_proxy_backup_on_remove | default(false) }}"
    bytefreezer_proxy_backup_dir: "{{ bytefreezer_proxy_backup_dir | default('/opt/backups/bytefreezer-proxy') }}"
    bytefreezer_proxy_remove_spooling_dir: "{{ bytefreezer_proxy_remove_spooling_dir | default(false) }}"

  pre_tasks:
    - name: Check if service exists
      ansible.builtin.stat:
        path: /etc/systemd/system/{{ bytefreezer_proxy_service_name }}.service
      register: service_exists

    - name: Display removal information
      debug:
        msg:
          - "Removing ByteFreezer Proxy service..."
          - "Service exists: {{ service_exists.stat.exists }}"
          - "Backup data: {{ bytefreezer_proxy_backup_on_remove | default(false) }}"

  tasks:
    - name: Stop and disable service
      systemd:
        name: "{{ bytefreezer_proxy_service_name }}"
        state: stopped
        enabled: no
        daemon_reload: yes
      when: service_exists.stat.exists
      ignore_errors: yes

    - name: Create backup directory
      ansible.builtin.file:
        path: "{{ bytefreezer_proxy_backup_dir | default('/opt/backups/bytefreezer-proxy') }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      when: bytefreezer_proxy_backup_on_remove | default(false)

    - name: Backup configuration and data
      ansible.builtin.shell: |
        tar -czf "{{ bytefreezer_proxy_backup_dir | default('/opt/backups/bytefreezer-proxy') }}/bytefreezer-proxy-removal-backup-{{ ansible_date_time.epoch }}.tar.gz" \
          --ignore-failed-read \
          "{{ bytefreezer_proxy_config_dir }}" \
          "{{ bytefreezer_proxy_log_dir }}" \
          "{{ bytefreezer_proxy_spooling_dir }}" \
          2>/dev/null || true
      when: bytefreezer_proxy_backup_on_remove | default(false)
      ignore_errors: yes

    - name: Remove systemd service file
      ansible.builtin.file:
        path: /etc/systemd/system/{{ bytefreezer_proxy_service_name }}.service
        state: absent
      notify: reload systemd

    - name: Remove logrotate configuration
      ansible.builtin.file:
        path: /etc/logrotate.d/bytefreezer-proxy
        state: absent

    - name: Remove installation directory
      ansible.builtin.file:
        path: "{{ bytefreezer_proxy_install_dir }}"
        state: absent

    - name: Remove configuration directory
      ansible.builtin.file:
        path: "{{ bytefreezer_proxy_config_dir }}"
        state: absent

    - name: Remove log directory
      ansible.builtin.file:
        path: "{{ bytefreezer_proxy_log_dir }}"
        state: absent

    - name: Remove spooling directory (only if explicitly requested)
      ansible.builtin.file:
        path: "{{ bytefreezer_proxy_spooling_dir }}"
        state: absent
      when: bytefreezer_proxy_remove_spooling_dir | default(false)

    - name: Remove system user
      ansible.builtin.user:
        name: "{{ bytefreezer_proxy_user }}"
        state: absent
        remove: yes

    - name: Remove system group
      ansible.builtin.group:
        name: "{{ bytefreezer_proxy_group }}"
        state: absent

  post_tasks:
    - name: Verify removal
      ansible.builtin.stat:
        path: /etc/systemd/system/{{ bytefreezer_proxy_service_name }}.service
      register: service_removed

    - name: Display removal status
      debug:
        msg:
          - "ByteFreezer Proxy complete removal completed!"
          - "Service removed: {{ not service_removed.stat.exists }}"
          - "Directories removed: {{ bytefreezer_proxy_install_dir }}, {{ bytefreezer_proxy_config_dir }}, {{ bytefreezer_proxy_log_dir }}"
          - "Spooling directory preserved: {{ bytefreezer_proxy_spooling_dir }} (unless bytefreezer_proxy_remove_spooling_dir=true)"
          - "System user and group removed"
          - "Backup created: {{ bytefreezer_proxy_backup_on_remove | default(false) }}"
          - "NOTE: Firewall rules and system tuning must be reverted manually"

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes